package com.nlan.appSpring.utils;

import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;
import java.util.Properties;

import org.hsqldb.Server;
import org.hsqldb.persist.HsqlProperties;
import org.hsqldb.server.ServerAcl.AclFormatException;

public class ServerHDBSQL {
	private static Server server;

	public static void main(String[] args) throws IOException, AclFormatException {
		System.out.println("server is running");
		runAndCreateDB();
	}

	public static void runAndCreateDB() throws IOException, AclFormatException {
		String TMP_DIR = "/build/test/";
		String dblocation = TMP_DIR + "db_items_storage";
		Properties database = database();
		HsqlProperties p = new HsqlProperties();

		p.setProperty("server.database.0", "mem" + dblocation);
		p.setProperty("server.dbname.0", "db_items_storage");
		p.setProperty("server.port", 3336);
		server = new Server();
		server.setProperties(p);
		server.start();

		Connection connection = null;
		Statement statement = null;

		try {
			Class.forName(database.getProperty("jdbc.driverClassName"));
		} catch (Exception e) {
			System.err.println("ERROR: failed to load HSQLDB JDBC driver.");
			e.printStackTrace();
			return;
		}

		try {
			connection = DriverManager.getConnection(database.getProperty("jdbc.url"));
		} catch (SQLException e) {
			e.printStackTrace();
		}
		if (connection == null) {
			System.out.println(" connection null");
			return;
		}
		try {
			statement = connection.createStatement();
			statement.executeUpdate("DROP SCHEMA PUBLIC CASCADE");
			
			createCategoryTable(statement);
			createItemTable(statement);
			createItemCategoryTable(statement);
			
			statement.close();
			connection.commit();
			connection.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	private static void createTable(String table, String query, Statement statement) throws SQLException
	{
		statement.executeUpdate("DROP TABLE IF EXISTS "+table+ "CASCADE");
		statement.executeUpdate(query);		
	}
	
	private static void createItemTable(Statement statement) throws SQLException
	{
		String table = "ITEM";
		String query = "CREATE TABLE "+table+" (ITEM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1)NOT NULL,"
				+ "ITEM_DESCRIPTION VARCHAR(100) NOT NULL,"
				+ "ITEM_NAME VARCHAR(45) NOT NULL,"
				+ "ITEM_IMAGE VARCHAR(45) NOT NULL,"
				+ "PRIMARY KEY (ITEM_ID)"
				+ ")";
		createTable(table, query, statement);
	}
	
	private static void createCategoryTable(Statement statement) throws SQLException
	{
		String table = "CATEGORY";
		String query = "CREATE TABLE "+table+" (CATEGORY_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1)NOT NULL,"
				+ "CATEGORY_DESCRIPTION VARCHAR(100) NOT NULL,"
				+ "CATEGORY_NAME VARCHAR(45) NOT NULL,"
				+ "CATEGORY_IMAGE VARCHAR(45) NOT NULL,"
				+ "PRIMARY KEY (CATEGORY_ID)"
				+ ")";
		createTable(table, query, statement);
	}
	
	private static void createItemCategoryTable(Statement statement) throws SQLException
	{
		String table = "ITEM_CATEGORY";
		String query = "CREATE TABLE "+table+" "
				+ "("
				+ "CATEGORY_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1)NOT NULL,"
				+ "ITEM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0, INCREMENT BY 1)NOT NULL,"
				+ "PRIMARY KEY (ITEM_ID, CATEGORY_ID),"
				+ "FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),"
				+ "FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)"
				+ ")";
		createTable(table, query, statement);
	}

	public static void closeServer() {
		if (Objects.nonNull(server)) {
			server.stop();
		}
	}

	private static Properties database() {
		Properties prop = new Properties();
		InputStream stream = null;

		ClassLoader loader = Thread.currentThread().getContextClassLoader();
		try {
			stream = loader.getResourceAsStream("database.properties");
		} finally {
			if (stream != null) {
				try {
					prop.load(stream);
					stream.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}

		}

		return prop;
	}
}
