/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nicol' at '7/3/16 8:34 PM' with Gradle 2.14
 *
 * @author nicol, @date 7/3/16 8:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
