/*DROP SCHEMA IF EXISTS `db_items_storage` CASCADE;*/

CREATE DATABASE IF NOT EXISTS `db_items_storage`;
USE `db_items_storage`;

CREATE TABLE IF NOT EXISTS `ITEM` ( 
				  `ITEM_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
				  `ITEM_DESCRIPTION` varchar(100) NOT NULL,
				  `ITEM_NAME` varchar(20) NOT NULL,
				  `ITEM_IMAGE` varchar(20) NOT NULL,
				   PRIMARY KEY (`ITEM_ID`) USING BTREE,
				   UNIQUE KEY `UNI_ITEM_NAME` (`ITEM_NAME`),
				   UNIQUE KEY `UNI_ITEM_ID` (`ITEM_ID`) USING BTREE
				   )ENGINE = InnoDB AUTO_INCREMENT = 0;
				   

CREATE TABLE IF NOT EXISTS `CATEGORY` (
				`CATEGORY_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
				`CATEGORY_DESCRIPTION` varchar(100) NOT NULL,
				`CATEGORY_NAME` varchar(50) NOT NULL,
				`CATEGORY_IMAGE` varchar(45) NOT NULL,
				 PRIMARY KEY (`CATEGORY_ID`) USING BTREE
				 )ENGINE = InnoDB AUTO_INCREMENT = 0;
				 
CREATE TABLE IF NOT EXISTS  `ITEM_CATEGORY` (
				`ITEM_ID` int(10) unsigned NOT NULL,
				`CATEGORY_ID` int(10) unsigned NOT NULL,
				PRIMARY KEY (`ITEM_ID`,`CATEGORY_ID`),
				CONSTRAINT `FK_CATEGORY_ID` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY` (`CATEGORY_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
				CONSTRAINT `FK_ITEM_ID` FOREIGN KEY (`ITEM_ID`) REFERENCES `ITEM` (`ITEM_ID`) ON DELETE CASCADE ON UPDATE CASCADE
				)ENGINE = InnoDB AUTO_INCREMENT = 0;
				 